package edu.berkeley.path.model_objects.scenario;

import core.*;

rule "Project ID of Scenario is not null or 0"
dialect "mvel"
dialect "java"
when
  $scenario : Scenario ( projectId == 0 || projectId == null)
then
  System.out.println("Error: Invalid Project ID. Cannot be null or 0.");
end

rule "Project ID of Scenario is an existing project in Database"
dialect "mvel"
dialect "java"
when
  $scenario : Scenario ( projectId != 0 && projectId != null)
then
  Long projectId = $scenario.getProjectId();
  java.sql.Connection dbConn = oraDatabase.doConnect();
  // check database for project ID
  String query = "read_projectID" + projectId;

  oraDatabaseReader.psCreate(dbConn,
  query,
  "SELECT * " +
  "FROM VIA.\"PROJECTS\" WHERE (\"ID\" = ?)",
  1
  );

  oraDatabaseReader.psSetParam(query, 1, oraSPEnums.spParamType.INT_VAR, projectId + "");
  oraDatabaseReader.psQuery(query);

  if (oraDatabaseReader.rsNext(query)) {
    System.out.println("Scenario's Project ID exists in Database.");
  } else {
    System.out.println("Error : Scenario's Project ID DOES NOT exist in Database.");
  }
end

rule "Network Name is not null or 0"
dialect "mvel"
dialect "java"
when
  $scenario : Scenario ( getListOfNetworks() )
then
  System.out.println("Error: Invalid Network Name. Cannot be null.");
end